apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadow
  template:
    metadata:
      labels:
        app: shadow
    spec:
      containers:
      - name: shadow
        image: abdullahi22/shadow:latest
        ports:
        - containerPort: 3000
